/**
 * scripts/setup-members.ts — Phase 0 de-risking & account setup.
 *
 * Run:  npm run setup            (do everything: generate → fund STX → verify)
 *       npm run setup generate   (only create + persist keys to .env.local)
 *       npm run setup fund       (only request testnet STX for all accounts)
 *       npm run setup verify     (only run the member→escrow split verification)
 *
 * What it does, idempotently:
 *   1. Ensures 7 managed testnet accounts exist (escrow + 6 members) and are
 *      persisted to .env.local as ESCROW_KEY / MEMBER_1_KEY … MEMBER_6_KEY.
 *   2. Funds each account with testnet STX (Hiro faucet) for gas.
 *   3. Verifies the FlowVault pipeline end-to-end: a real member→escrow SPLIT
 *      (createStrategy + deposit) confirmed on-chain, printed as an explorer
 *      link. This is Phase 0's "Done when".
 *
 * USDCx note: the demo USDCx token is protocol-mint gated (no public faucet
 * function), so members must be funded with USDCx out-of-band (FlowVault dApp
 * faucet / maintainer / a SIP-010 transfer from a holder). If a member has no
 * USDCx yet, the script still proves the on-chain path by broadcasting a real
 * `set-routing-rules` tx, and tells you exactly what remains.
 *
 * ⚠️ Testnet only. Never place mainnet keys in .env.local.
 */
import { config as loadEnv } from "dotenv";
import { promises as fs } from "fs";
import path from "path";
import { getAddressFromPrivateKey, randomPrivateKey } from "@stacks/transactions";
import { NETWORK, FLOWVAULT, CIRCLE } from "../lib/constants";
import { addressUrl, txUrl, waitForTx, HIRO_API } from "../lib/explorer";
import { vaultFor, setStrategy, deposit, readState } from "../lib/flow";
import { MEMBER_PROFILES, ESCROW_PROFILE } from "../lib/members";
import { tokenToMicro } from "flowvault-sdk";

loadEnv({ path: ".env.local" });

const ENV_PATH = path.join(process.cwd(), ".env.local");
const MEMBER_VARS = MEMBER_PROFILES.map((_, i) => `MEMBER_${i + 1}_KEY`);
const ALL_VARS = ["ESCROW_KEY", ...MEMBER_VARS];

/** Minimum STX (micro) we consider "funded enough" to broadcast contract calls. */
const MIN_STX_MICRO = 1_000_000n; // 1 STX
const BOND_MICRO = tokenToMicro(CIRCLE.bond);

type Role = { var: string; label: string; emoji: string };
const ROLES: Role[] = [
  { var: "ESCROW_KEY", label: ESCROW_PROFILE.name, emoji: ESCROW_PROFILE.emoji },
  ...MEMBER_PROFILES.map((m, i) => ({
    var: MEMBER_VARS[i],
    label: `${m.name} (${m.city})`,
    emoji: m.emoji,
  })),
];

interface Account {
  role: Role;
  key: string;
  address: string;
}

// ---------------------------------------------------------------------------
// Small HTTP helpers against the Hiro testnet API.
// ---------------------------------------------------------------------------

async function stxBalanceMicro(address: string): Promise<bigint> {
  const res = await fetch(`${HIRO_API}/extended/v1/address/${address}/stx`);
  if (!res.ok) return 0n;
  const data = (await res.json()) as { balance?: string };
  return BigInt(data.balance ?? "0");
}

/** USDCx balance (micro) from the account's fungible-token balances. */
async function usdcxBalanceMicro(address: string): Promise<bigint> {
  const res = await fetch(`${HIRO_API}/extended/v1/address/${address}/balances`);
  if (!res.ok) return 0n;
  const data = (await res.json()) as {
    fungible_tokens?: Record<string, { balance?: string }>;
  };
  const prefix = `${FLOWVAULT.tokenContractAddress}.${FLOWVAULT.tokenContractName}::`;
  for (const [assetId, info] of Object.entries(data.fungible_tokens ?? {})) {
    if (assetId.startsWith(prefix)) return BigInt(info.balance ?? "0");
  }
  return 0n;
}

/** Request testnet STX from the Hiro faucet. Returns the funding txid, if any. */
async function requestStx(address: string): Promise<string | null> {
  const res = await fetch(
    `${HIRO_API}/extended/v1/faucets/stx?address=${address}`,
    { method: "POST" }
  );
  if (!res.ok) return null;
  const data = (await res.json()) as { success?: boolean; txId?: string };
  return data.success ? data.txId ?? null : null;
}

// ---------------------------------------------------------------------------
// .env.local read / write.
// ---------------------------------------------------------------------------

async function readEnvFile(): Promise<Record<string, string>> {
  try {
    const raw = await fs.readFile(ENV_PATH, "utf8");
    const out: Record<string, string> = {};
    for (const line of raw.split(/\r?\n/)) {
      const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)\s*$/);
      if (m) out[m[1]] = m[2];
    }
    return out;
  } catch {
    return {};
  }
}

async function writeEnvFile(vars: Record<string, string>): Promise<void> {
  const header =
    "# Sanctuary managed testnet signing keys — generated by scripts/setup-members.ts\n" +
    "# TESTNET ONLY. Do not commit (gitignored via .env*.local).\n\n";
  const body = ALL_VARS.map((k) => `${k}=${vars[k] ?? ""}`).join("\n") + "\n";
  await fs.writeFile(ENV_PATH, header + body, "utf8");
}

// ---------------------------------------------------------------------------
// Steps.
// ---------------------------------------------------------------------------

/** Ensure every role has a key; generate + persist any that are missing. */
async function ensureAccounts(): Promise<Account[]> {
  const env = { ...(await readEnvFile()), ...pickProcessEnv() };
  let generated = 0;

  for (const v of ALL_VARS) {
    if (!env[v]) {
      env[v] = randomPrivateKey();
      generated++;
    }
  }

  if (generated > 0) {
    await writeEnvFile(env);
    console.log(`🔑 Generated ${generated} new key(s) → .env.local`);
  } else {
    console.log("🔑 Reusing existing keys from .env.local");
  }

  // Make them available to this process (lib/env.ts reads process.env).
  for (const v of ALL_VARS) process.env[v] = env[v];

  const accounts: Account[] = ROLES.map((role) => {
    const key = env[role.var];
    return { role, key, address: getAddressFromPrivateKey(key, NETWORK) };
  });

  console.log("\n👥 Roster");
  for (const a of accounts) {
    console.log(`   ${a.role.emoji} ${a.role.label.padEnd(24)} ${a.address}`);
    console.log(`      ${addressUrl(a.address)}`);
  }
  return accounts;
}

function pickProcessEnv(): Record<string, string> {
  const out: Record<string, string> = {};
  for (const v of ALL_VARS) if (process.env[v]) out[v] = process.env[v]!;
  return out;
}

/** Fund any under-funded account with testnet STX and wait for confirmation. */
async function fundStx(accounts: Account[]): Promise<void> {
  console.log("\n💧 Funding STX (gas)…");
  const pending: { address: string; txid: string }[] = [];

  for (const a of accounts) {
    const bal = await stxBalanceMicro(a.address);
    if (bal >= MIN_STX_MICRO) {
      console.log(`   ✓ ${a.role.label}: already funded (${fmt(bal)} STX)`);
      continue;
    }
    const txid = await requestStx(a.address);
    if (txid) {
      console.log(`   → ${a.role.label}: faucet tx ${txUrl(txid)}`);
      pending.push({ address: a.address, txid });
    } else {
      console.log(`   ⚠ ${a.role.label}: faucet declined (rate-limited?) — retry later`);
    }
    await sleep(1500); // be gentle with the faucet
  }

  if (pending.length === 0) return;
  console.log("   ⏳ Waiting for faucet txs to confirm…");
  for (const p of pending) {
    const status = await waitForTx(p.txid, { timeoutMs: 300_000 });
    console.log(`   ${status === "success" ? "✓" : "⚠"} ${p.address}: ${status}`);
  }
}

/**
 * Phase 0 "Done when": broadcast a real member→escrow SPLIT and confirm it.
 * Falls back to a real set-routing-rules tx (pipeline proof) if the member has
 * no USDCx yet.
 */
async function verifySplit(accounts: Account[]): Promise<void> {
  const escrow = accounts[0];
  const member = accounts[1]; // Amara
  console.log(`\n🔎 Phase 0 verification — ${member.role.label} → ${escrow.role.label}`);

  const stx = await stxBalanceMicro(member.address);
  if (stx < MIN_STX_MICRO) {
    console.log(`   ✗ ${member.role.label} has insufficient STX for gas. Run: npm run setup fund`);
    return;
  }

  const usdcx = await usdcxBalanceMicro(member.address);
  console.log(`   USDCx balance: ${fmt(usdcx)} (need ${fmt(BOND_MICRO)} for the split)`);

  const vault = vaultFor(member.key);
  const strategy = {
    splitAddress: escrow.address,
    split: CIRCLE.bond,
    lock: "0",
  };

  if (usdcx < BOND_MICRO) {
    // No USDCx: prove the on-chain pipeline with a real set-routing-rules tx.
    console.log("   ⚠ No USDCx yet — broadcasting a real set-routing-rules tx to prove the pipeline.");
    const strat = await setStrategy(vault, strategy);
    console.log(`   → set-routing-rules: ${txUrl(strat.txid)}`);
    const status = await waitForTx(strat.txid, { timeoutMs: 300_000 });
    console.log(`   ${status === "success" ? "✓" : "⚠"} set-routing-rules ${status}`);
    console.log(
      "\n   ⏭  To finish Phase 0, fund this member with USDCx, then re-run: npm run setup verify\n" +
        `       member: ${member.address}`
    );
    return;
  }

  // Full split: set rules, confirm, deposit (routing executes atomically).
  console.log("   1/2 set-routing-rules (split → escrow)…");
  const strat = await setStrategy(vault, strategy);
  console.log(`       ${txUrl(strat.txid)}`);
  const s1 = await waitForTx(strat.txid, { timeoutMs: 300_000 });
  if (s1 !== "success") return void console.log(`   ✗ set-routing-rules ${s1}`);

  console.log("   2/2 deposit (bond splits to escrow)…");
  const dep = await deposit(vault, CIRCLE.bond);
  console.log(`       ${txUrl(dep.txid)}`);
  const s2 = await waitForTx(dep.txid, { timeoutMs: 300_000 });
  if (s2 !== "success") return void console.log(`   ✗ deposit ${s2}`);

  const escrowState = await readState(vaultFor(escrow.key), escrow.address);
  console.log("\n   ✅ Phase 0 complete — real testnet SPLIT confirmed on-chain.");
  console.log(`      deposit tx: ${txUrl(dep.txid)}`);
  console.log(`      escrow vault: total=${escrowState.total} unlocked=${escrowState.unlocked} USDCx`);
  console.log(`      ${addressUrl(escrow.address)}`);
}

// ---------------------------------------------------------------------------
// Utils + main.
// ---------------------------------------------------------------------------

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));
const fmt = (micro: bigint) => (Number(micro) / 1_000_000).toString();

async function main() {
  const step = process.argv[2] ?? "all";
  console.log(`🏛  Sanctuary setup — network: ${NETWORK}, step: ${step}\n`);

  const accounts = await ensureAccounts();
  if (step === "generate") return;

  if (step === "all" || step === "fund") await fundStx(accounts);
  if (step === "fund") return;

  if (step === "all" || step === "verify") await verifySplit(accounts);
}

main().catch((err) => {
  console.error("\n💥 setup failed:", err instanceof Error ? err.message : err);
  process.exit(1);
});
